"""

	Crop your dataset guided by json generated by labelme.

"""

import os.path
import json
import cv2

folder_name = "shangHeDou_guanZhuangMian_cut_resize" # your data folder's name
work_dir = ".\\" + folder_name # direction of your data
fileType = '.jpg' # your data type

for i in range(200):
	img_path = os.path.join(work_dir, str(i + 1) + fileType)
	img = cv2.imread(img_path)
	resized = cv2.resize(img, (512, 512))
	cv2.imwrite(img_path, resized, [int(cv2.IMWRITE_JPEG_QUALITY), 100])

print ('Done successfully!')